# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "test"
  
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "vtimd/codefresh-blog"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  test:
    title: "Running Cypress test"
    type: "freestyle" # Run any command
    image: cypress/base
    working_directory: "${{clone}}" # Running command where code cloned
    commands:
      - npm ci
      - $(npm bin)/print-env CI
      - npm run cy:verify
      - (npm run start:ci &)
      - npm run e2e
    stage: "test"
